
"use client";

import Link from "next/link";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";

import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { useRouter } from "next/navigation";
import { useToast } from "@/hooks/use-toast";
import { useCrypto } from "@/hooks/use-crypto";

const formSchema = z.object({
  email: z.string().email({ message: "Please enter a valid email." }),
  password: z.string().min(1, { message: "Password is required." }),
  // In a real app with passwordless/recovery phrase login, you'd have a separate field for this.
  // For simulation, we'll just re-use the password field.
});

// This is a MOCK key vault that would be fetched from Firestore after user authenticates.
const MOCK_KEY_VAULT = {
    // This value would be generated by the signup flow `encryptPrivateKey` function
    "encryptedKey": "S5s...EXAMPLE...A==", 
    "salt": "Salty...EXAMPLE...A==",
    "iv": "IV...EXAMPLE...A==",
};
// This is the MOCK recovery phrase that was used to encrypt the key.
const MOCK_RECOVERY_PHRASE = "legal ... example ... phrase";


export default function LoginForm() {
  const router = useRouter();
  const { toast } = useToast();
  const { isProcessing, decryptPrivateKey } = useCrypto();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      email: "",
      password: "",
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    // In a real app, you would handle authentication here.
    // 1. Authenticate with Firebase Auth (email/password).
    // 2. Fetch the user's encrypted `key_vault` from Firestore.
    // 3. Prompt for recovery phrase if the key isn't in memory/session.
    
    // For now, we'll simulate the decryption process.
    console.log("--- SECURE LOGIN ---");
    console.log("Attempting to decrypt key vault for:", values.email);
    // In this demo, the password field is used for the recovery phrase.
    // In a real app, this might be a separate, dedicated input.
    const recoveryPhrase = values.password; 
    console.log("Using recovery phrase from input:", recoveryPhrase);

    // For this demo, we use a mock vault. In a real app, MOCK_KEY_VAULT would be fetched from Firestore.
    const decryptedKey = await decryptPrivateKey(MOCK_KEY_VAULT, recoveryPhrase);

    if (decryptedKey) {
        console.log("Decryption successful! Private key rehydrated in memory:", decryptedKey);
        console.log("This key can now be stored in-memory (e.g., using a state manager like Zustand) for the session.");
        toast({
            title: "Login Successful",
            description: "Secure key rehydrated. Redirecting...",
        });
        router.push("/dashboard");
    } else {
        console.error("Decryption failed. The provided recovery phrase may be incorrect.");
        toast({
            variant: "destructive",
            title: "Login Failed",
            description: "Could not decrypt key vault. Please check your recovery phrase.",
        });
    }
     console.log("--- END SECURE LOGIN ---");
  }

  return (
    <Card className="glass-card">
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)}>
          <CardHeader>
            <CardTitle className="font-headline">Log In</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <FormField
              control={form.control}
              name="email"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Email</FormLabel>
                  <FormControl>
                    <Input placeholder="name@example.com" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="password"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Password or Recovery Phrase</FormLabel>
                  <FormControl>
                    <Input type="password" placeholder="••••••••" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
          </CardContent>
          <CardFooter className="flex flex-col gap-4">
            <Button type="submit" className="w-full" disabled={isProcessing}>
              Log In
            </Button>
            <p className="text-sm text-muted-foreground">
                Don&apos;t have an account?{" "}
                <Link href="/signup" className="text-primary hover:underline">
                    Sign Up
                </Link>
            </p>
          </CardFooter>
        </form>
      </Form>
    </Card>
  );
}
